name: Deploy NotesApp to Azure

on:
  push:
    branches:
      - main   # deploys when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false   # 🚀 ignore submodules

      # 2️⃣ Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "NotesApp"                    # your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPPUBLISHPROFILE }}
          package: .
